### ISSUE TITLE
Query URIEncoded twice

### ISSUE THREAD

**Issue by denis-mludek** [RickWong/fetch-plus#13]
Hi,

Whenever I pass a text query with spaces, the spaces are replaced with %2520 instead of %20, am I doing something wrong here ?

```
let q = 'test fetch plus'  
endpoint.browse(
      URI,
      {query: {q}}
    )
```

Request query result : `&q=test%2520fetch%2520plus`

**Comment by RickWong** [comment]
Thanks @denis-mludek I found the problem. The query-string package already handles encoding, so it's indeed encoding twice on this line:

https://github.com/RickWong/fetch-plus/blob/534357191691131aa8a94665f0d4f1ee8611856c/packages/fetch-plus/src/index.js#L130

Will publish fix tomorrow.
